CL SCR;
ALTER SESSION SET CURRENT_SCHEMA = PTTK03_QLTUYENDUNG;

CREATE OR REPLACE PROCEDURE USP_DROP_USERS
AS CURSOR CUR_NHANSU IS (SELECT MANV FROM NHANSU
        WHERE MANV IN (SELECT USERNAME FROM ALL_USERS));
BEGIN FOR USR IN CUR_NHANSU LOOP
        EXECUTE IMMEDIATE 'DROP USER ' || USR.MANV;
    END LOOP;
END;
/
EXEC USP_DROP_USERS();

ALTER SESSION SET CURRENT_SCHEMA = SYS;
DECLARE CURSOR CUR IS (SELECT "ROLE" AS RO FROM DBA_ROLES
        WHERE "ROLE" LIKE 'RL_N3QLTD%');
BEGIN FOR RL IN CUR LOOP
        EXECUTE IMMEDIATE 'DROP ROLE ' || RL.RO;
    END LOOP;
END;
/

DROP USER PTTK03_QLTUYENDUNG CASCADE;