CL SCR;

BEGIN EXECUTE IMMEDIATE 'DROP USER PTTK03_QLTUYENDUNG CASCADE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/
CREATE USER PTTK03_QLTUYENDUNG IDENTIFIED BY 123;

GRANT DBA TO PTTK03_QLTUYENDUNG;
GRANT CREATE SESSION TO PTTK03_QLTUYENDUNG WITH ADMIN OPTION;
GRANT CREATE USER, DROP USER TO PTTK03_QLTUYENDUNG;
GRANT GRANT ANY ROLE TO PTTK03_QLTUYENDUNG;

ALTER SESSION SET CURRENT_SCHEMA = PTTK03_QLTUYENDUNG;

CREATE TABLE CHUCVU(
    MACV NUMBER(2) PRIMARY KEY,
    TENCV VARCHAR2(50),
    VIETTAT VARCHAR2(2)
);

CREATE TABLE HTDANGTUYEN(
    MAHT NUMBER(2) PRIMARY KEY,
    TENHT VARCHAR2(100),
    MOTA VARCHAR2(200)
);

CREATE TABLE HTTHANHTOAN(
    MAHT NUMBER(2) PRIMARY KEY,
    TENHT VARCHAR2(100),
    MOTA VARCHAR2(200)
);

CREATE TABLE PTTHANHTOAN(
    MAPT NUMBER(2) PRIMARY KEY,
    TENPT VARCHAR2(100),
    MOTA VARCHAR2(200)
);

CREATE TABLE TINHTRANGHS(
    MATT NUMBER(2) PRIMARY KEY,
    TENTT VARCHAR2(100)
);

CREATE TABLE LOAIGIAYTO(
    MALOAI NUMBER(2) PRIMARY KEY,
    TENLOAI VARCHAR2(100)
);

CREATE TABLE NHANSU(
    MANV VARCHAR2(8) PRIMARY KEY,
    HOTEN VARCHAR2(50),
    DCHI VARCHAR2(200),
    SDT VARCHAR2(11),
    EMAIL VARCHAR2(100),
    CHUCVU NUMBER(2),

    CONSTRAINT FK_NHANSU_CHUCVU
    FOREIGN KEY(CHUCVU) REFERENCES CHUCVU(MACV)
    ON DELETE SET NULL
);

CREATE TABLE UNGVIEN(
    MAUV VARCHAR2(8) PRIMARY KEY,
    HOTEN VARCHAR2(50),
    DCHI VARCHAR2(200),
    SDT VARCHAR2(11),
    EMAIL VARCHAR2(100),
    NVPHUTRACH VARCHAR2(8),

    CONSTRAINT FK_UNGVIEN_NHANSU
    FOREIGN KEY(NVPHUTRACH) REFERENCES NHANSU(MANV)
    ON DELETE SET NULL
);

CREATE TABLE DOANHNGHIEP(
    MADN VARCHAR2(8) PRIMARY KEY,
    TENCTY VARCHAR2(100),
    MASOTHUE VARCHAR2(14) CONSTRAINT UNQ_DOANHNGHIEP_MASOTHUE UNIQUE,
    NGDAIDIEN VARCHAR2(50),
    DCHI VARCHAR2(200),
    EMAIL VARCHAR2(100) CONSTRAINT UNQ_DOANHNGHIEP_EMAIL UNIQUE,
    NGAYLAPHD DATE,
    NGAYHHHD DATE,
    NVPHUTRACH VARCHAR2(8),

    CONSTRAINT CHK_DOANHNGHIEP_NGAY CHECK(NGAYLAPHD < NGAYHHHD),

    CONSTRAINT FK_DOANHNGHIEP_NHANSU
    FOREIGN KEY(NVPHUTRACH) REFERENCES NHANSU(MANV)
    ON DELETE SET NULL
);

CREATE TABLE PTTDANGTUYEN(
    MADN VARCHAR2(8),
    MAPHIEU VARCHAR2(8),
    VITRIUT VARCHAR2(100),
    SOLUONGTD INT,
    NGAYBD DATE,
    NGAYKT DATE,
    YEUCAUUV VARCHAR2(200),
    TONGTIEN INT,
    TIENDATRA INT,
    HTTHANHTOAN NUMBER(2),
    NVLAP VARCHAR2(8),

    CONSTRAINT PK_PTTDANGTUYEN PRIMARY KEY(MADN, MAPHIEU),
    CONSTRAINT CHK_PTTDANGTUYEN_NGAY CHECK(NGAYBD < NGAYKT),

    CONSTRAINT FK_PTTDANGTUYEN_HTTHANHTOAN
    FOREIGN KEY(HTTHANHTOAN) REFERENCES HTTHANHTOAN(MAHT)
    ON DELETE SET NULL,

    CONSTRAINT FK_PTTDANGTUYEN_NHANSU
    FOREIGN KEY(NVLAP) REFERENCES NHANSU(MANV)
    ON DELETE SET NULL
);

CREATE TABLE HOSOUNGTUYEN(
    MAUV VARCHAR2(8),
    MADN VARCHAR2(8),
    MAPHIEU VARCHAR2(8),
    DOUUTIEN NUMBER(2),
    GHICHU VARCHAR2(200),
    TINHTRANG NUMBER(2),
    NVDUYET VARCHAR2(8),

    CONSTRAINT PK_HOSOUNGTUYEN PRIMARY KEY(MAUV, MADN, MAPHIEU),
    CONSTRAINT CHK_HOSOUNGTUYEN_DOUUTIEN
    CHECK(1 <= DOUUTIEN AND DOUUTIEN <= 10),

    CONSTRAINT FK_HOSOUNGTUYEN_UNGVIEN
    FOREIGN KEY(MAUV) REFERENCES UNGVIEN(MAUV)
    ON DELETE CASCADE,

    CONSTRAINT FK_HOSOUNGTUYEN_PTTDANGTUYEN
    FOREIGN KEY(MADN, MAPHIEU) REFERENCES PTTDANGTUYEN(MADN, MAPHIEU)
    ON DELETE CASCADE,

    CONSTRAINT FK_HOSOUNGTUYEN_TINHTRANGHS
    FOREIGN KEY(TINHTRANG) REFERENCES TINHTRANGHS(MATT)
    ON DELETE SET NULL,

    CONSTRAINT FK_HOSOUNGTUYEN_NHANSU
    FOREIGN KEY(NVDUYET) REFERENCES NHANSU(MANV)
    ON DELETE SET NULL
);

CREATE TABLE GIAYTOUT(
    MAUV VARCHAR2(8),
    MADN VARCHAR2(8),
    MAPHIEU VARCHAR2(8),
    MAGIAY NUMBER(2),
    THONGTIN VARCHAR2(200),
    LOAIGIAY NUMBER(2),

    CONSTRAINT PK_GIAYTOUT PRIMARY KEY(MAUV, MADN, MAPHIEU, MAGIAY),

    CONSTRAINT FK_GIAYTOUT_HOSOUNGTUYEN
    FOREIGN KEY(MAUV, MADN, MAPHIEU) REFERENCES HOSOUNGTUYEN(MAUV, MADN, MAPHIEU)
    ON DELETE CASCADE,

    CONSTRAINT FK_GIAYTOUT_LOAIGIAYTO
    FOREIGN KEY(LOAIGIAY) REFERENCES LOAIGIAYTO(MALOAI)
    ON DELETE SET NULL
);

CREATE TABLE PDKQUANGCAO(
    MADN VARCHAR2(8),
    MAPHIEU VARCHAR2(8),
    MAHT NUMBER(2),
    NGAYBD DATE,
    NGAYKT DATE,

    CONSTRAINT PK_PDKQUANGCAO PRIMARY KEY(MADN, MAPHIEU, MAHT),
    CONSTRAINT CHK_PDKQUANGCAO_NGAY CHECK(NGAYBD < NGAYKT),

    CONSTRAINT FK_PDKQUANGCAO_PTTDANGTUYEN
    FOREIGN KEY(MADN, MAPHIEU) REFERENCES PTTDANGTUYEN(MADN, MAPHIEU)
    ON DELETE CASCADE,

    CONSTRAINT FK_PDKQUANGCAO_HTDANGTUYEN
    FOREIGN KEY(MAHT) REFERENCES HTDANGTUYEN(MAHT)
    ON DELETE CASCADE
);

CREATE TABLE CTHOADON(
    MADN VARCHAR2(8),
    MAPHIEU VARCHAR2(8),
    MACT NUMBER(2),
    SOTIEN INT,
    NGAYTRA DATE,
    PTTHANHTOAN NUMBER(2),

    CONSTRAINT PK_CTHOADON PRIMARY KEY(MADN, MAPHIEU, MACT),

    CONSTRAINT FK_CTHOADON_PTTDANGTUYEN
    FOREIGN KEY(MADN, MAPHIEU) REFERENCES PTTDANGTUYEN(MADN, MAPHIEU)
    ON DELETE CASCADE,

    CONSTRAINT FK_CTHOADON_PTTHANHTOAN
    FOREIGN KEY(PTTHANHTOAN) REFERENCES PTTHANHTOAN(MAPT)
    ON DELETE SET NULL
);

CREATE TABLE DNTIEMNANG(
    MADN VARCHAR2(8),
    LDDANHGIA VARCHAR2(8),
    TIEMNANG NUMBER(2),
    GHICHU VARCHAR2(200),
    NGAYCAPNHAT DATE,

    CONSTRAINT PK_DNTIEMNANG PRIMARY KEY(MADN, LDDANHGIA),
    CONSTRAINT CHK_DNTIEMNANG_TIEMNANG
    CHECK(1 <= TIEMNANG AND TIEMNANG <= 10),

    CONSTRAINT FK_DNTIEMNANG_DOANHNGHIEP
    FOREIGN KEY(MADN) REFERENCES DOANHNGHIEP(MADN)
    ON DELETE CASCADE,

    CONSTRAINT FK_DNTIEMNANG_NHANSU
    FOREIGN KEY(LDDANHGIA) REFERENCES NHANSU(MANV)
    ON DELETE CASCADE
);

CREATE TABLE CHIENLUOCUUDAI(
    MACL VARCHAR2(8) PRIMARY KEY,
    TENCL VARCHAR2(100) CONSTRAINT UNQ_CHIENLUOCUUDAI_TENCL UNIQUE,
    MOTA VARCHAR2(200),
    LDDEXUAT VARCHAR2(8),

    CONSTRAINT FK_CHIENLUOCUUDAI_NHANSU
    FOREIGN KEY(LDDEXUAT) REFERENCES NHANSU(MANV)
    ON DELETE SET NULL
);

CREATE TABLE CLAPDUNG(
    MADN VARCHAR2(8),
    MACL VARCHAR2(8),
    NGAYBD DATE,
    NGAYKT DATE,

    CONSTRAINT PK_CLAPDUNG PRIMARY KEY(MADN, MACL),
    CONSTRAINT CHK_CLAPDUNG_NGAY CHECK(NGAYBD < NGAYKT),

    CONSTRAINT FK_CLAPDUNG_DOANHNGHIEP
    FOREIGN KEY(MADN) REFERENCES DOANHNGHIEP(MADN)
    ON DELETE CASCADE,

    CONSTRAINT FK_CLAPDUNG_CHIENLUOCUUDAI
    FOREIGN KEY(MACL) REFERENCES CHIENLUOCUUDAI(MACL)
    ON DELETE CASCADE
);