CL SCR;
ALTER SESSION SET CURRENT_SCHEMA = PTTK03_QLTUYENDUNG;

CREATE OR REPLACE FUNCTION UFN_MAKE_ID(RL VARCHAR2, CID VARCHAR2)
RETURN VARCHAR2 AS NID VARCHAR2(8); BEGIN
    IF CID IS NULL THEN NID := 'N3' || RL || '0001'; RETURN NID; END IF;
    NID := TO_NUMBER(SUBSTR(CID, 5)) + 1;
    RETURN 'N3' || RL || LPAD(NID, 4, '0');
END;
/

/* DOANHNGHIEP
 */
CREATE OR REPLACE PROCEDURE USP_DOANHNGHIEP_INS(
    ITENCTY VARCHAR2, IMASOTHUE VARCHAR2, INGDAIDIEN VARCHAR2, IDCHI VARCHAR2,
    IEMAIL VARCHAR2, INGAYLAPHD VARCHAR2, INGAYHHHD VARCHAR2, INVPHUTRACH VARCHAR2
) AS IMADN VARCHAR2(8); CNT INT; BEGIN
    SELECT COUNT(MADN) INTO CNT FROM DOANHNGHIEP WHERE MASOTHUE = IMASOTHUE;
    IF CNT != 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'MASOTHUE ALREADY EXISTS!'); END IF;

    SELECT COUNT(MADN) INTO CNT FROM DOANHNGHIEP WHERE EMAIL = IEMAIL;
    IF CNT != 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'EMAIL ALREADY EXISTS!'); END IF;

    SELECT MADN INTO IMADN FROM DOANHNGHIEP
    WHERE MADN = (SELECT MAX(MADN) FROM DOANHNGHIEP);
    IMADN := UFN_MAKE_ID('DN', IMADN);

    INSERT INTO DOANHNGHIEP VALUES (IMADN, ITENCTY, IMASOTHUE, INGDAIDIEN,
        IDCHI, IEMAIL, TO_DATE(INGAYLAPHD, 'DD/MM/YYYY'),
        TO_DATE(INGAYHHHD, 'DD/MM/YYYY'), INVPHUTRACH);
END;
/
