CL SCR;
ALTER SESSION SET CURRENT_SCHEMA = PTTK03_QLTUYENDUNG;

CREATE OR REPLACE PROCEDURE USP_CREATE_USER
AS CURSOR CUR_NHANSU IS (SELECT MANV FROM NHANSU
        WHERE MANV NOT IN (SELECT USERNAME FROM ALL_USERS));
BEGIN FOR USR IN CUR_NHANSU LOOP
        EXECUTE IMMEDIATE 'CREATE USER ' || USR.MANV || ' IDENTIFIED BY 123';
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ' || USR.MANV;
    END LOOP;
END;
/
EXEC USP_CREATE_USER();

CREATE OR REPLACE PROCEDURE USP_ASSIGN_ROLE(
    RL VARCHAR2, WHO VARCHAR2, TAB VARCHAR2, COLN VARCHAR2
) AS CUR SYS_REFCURSOR; USR VARCHAR2(8);
BEGIN OPEN CUR FOR 'SELECT ' || COLN || ' FROM ' || TAB
        || ' WHERE ' || COLN || ' LIKE ''N3' || WHO || '%'' AND '
        || COLN || ' IN (SELECT USERNAME FROM ALL_USERS)';
    LOOP FETCH CUR INTO USR; EXIT WHEN CUR%NOTFOUND;
        EXECUTE IMMEDIATE 'GRANT RL_N3QLTD_' || RL || ' TO ' || USR;
    END LOOP;
    CLOSE CUR;
END;
/

/* NHANVIEN
 */
CREATE ROLE RL_N3QLTD_NV;
EXEC USP_ASSIGN_ROLE('NV', 'NV', 'NHANSU', 'MANV');

GRANT EXECUTE ON USP_DOANHNGHIEP_INS TO RL_N3QLTD_NV;

/* LANHDAO
 */
CREATE ROLE RL_N3QLTD_LD;
EXEC USP_ASSIGN_ROLE('LD', 'LD', 'NHANSU', 'MANV');