CL SCR;
ALTER SESSION SET CURRENT_SCHEMA = PTTK03_QLTUYENDUNG;

CREATE OR REPLACE PROCEDURE USP_CREATE_USER
AS CURSOR CUR_NHANSU IS (SELECT MANV FROM NHANSU
        WHERE MANV NOT IN (SELECT USERNAME FROM ALL_USERS));
BEGIN FOR USR IN CUR_NHANSU LOOP
        EXECUTE IMMEDIATE 'CREATE USER ' || USR.MANV || ' IDENTIFIED BY 123';
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ' || USR.MANV;
    END LOOP;
END;
/
EXEC USP_CREATE_USER();

CREATE OR REPLACE PROCEDURE USP_ASSIGN_ROLE(
    RL VARCHAR2, WHO VARCHAR2, TAB VARCHAR2, COLN VARCHAR2
) AS CUR SYS_REFCURSOR; USR VARCHAR2(8);
BEGIN OPEN CUR FOR 'SELECT ' || COLN || ' FROM ' || TAB
        || ' WHERE ' || COLN || ' LIKE ''N3' || WHO || '%'' AND '
        || COLN || ' IN (SELECT USERNAME FROM ALL_USERS)';
    LOOP FETCH CUR INTO USR; EXIT WHEN CUR%NOTFOUND;
        EXECUTE IMMEDIATE 'GRANT RL_N3QLTD_' || RL || ' TO ' || USR;
    END LOOP;
    CLOSE CUR;
END;
/

/* NHANVIEN
 */
CREATE ROLE RL_N3QLTD_NV;
EXEC USP_ASSIGN_ROLE('NV', 'NV', 'NHANSU', 'MANV');

GRANT SELECT ON HTDANGTUYEN TO RL_N3QLTD_NV;
GRANT SELECT ON HTTHANHTOAN TO RL_N3QLTD_NV;
GRANT SELECT ON PTTHANHTOAN TO RL_N3QLTD_NV;

GRANT SELECT, UPDATE(NGAYLAPHD, NGAYHHHD) ON DOANHNGHIEP TO RL_N3QLTD_NV;
GRANT SELECT ON UNGVIEN TO RL_N3QLTD_NV;
GRANT SELECT ON PTTDANGTUYEN TO RL_N3QLTD_NV;

GRANT SELECT, INSERT, UPDATE(DOUUTIEN, GHICHU, TINHTRANG, NVDUYET)
ON HOSOUNGTUYEN TO RL_N3QLTD_NV;

GRANT SELECT ON GIAYTOUT TO RL_N3QLTD_NV;
GRANT SELECT ON PDKQUANGCAO TO RL_N3QLTD_NV;
GRANT SELECT ON CTHOADON TO RL_N3QLTD_NV;
GRANT SELECT ON CHIENLUOCUUDAI TO RL_N3QLTD_NV;
GRANT SELECT ON CLAPDUNG TO RL_N3QLTD_NV;

GRANT EXECUTE ON USP_DOANHNGHIEP_INS TO RL_N3QLTD_NV;
GRANT EXECUTE ON USP_UNGVIEN_INS TO RL_N3QLTD_NV;
GRANT EXECUTE ON USP_PTTDANGTUYEN_INS TO RL_N3QLTD_NV;
GRANT EXECUTE ON USP_GIAYTOUT_INS TO RL_N3QLTD_NV;
GRANT EXECUTE ON USP_PDKQUANGCAO_INS TO RL_N3QLTD_NV;
GRANT EXECUTE ON USP_CTHOADON_INS TO RL_N3QLTD_NV;

/* LANHDAO
 */
CREATE ROLE RL_N3QLTD_LD;
EXEC USP_ASSIGN_ROLE('LD', 'LD', 'NHANSU', 'MANV');

GRANT SELECT ON NHANSU TO RL_N3QLTD_LD;
GRANT SELECT ON DOANHNGHIEP TO RL_N3QLTD_LD;
GRANT SELECT ON PTTDANGTUYEN TO RL_N3QLTD_LD;
GRANT SELECT ON HOSOUNGTUYEN TO RL_N3QLTD_LD;

GRANT SELECT, INSERT, UPDATE(TIEMNANG, GHICHU, NGAYCAPNHAT), DELETE
ON DNTIEMNANG TO RL_N3QLTD_LD;

GRANT SELECT, UPDATE(TENCL, MOTA, LDDEXUAT)
ON CHIENLUOCUUDAI TO RL_N3QLTD_LD;

GRANT EXECUTE ON USP_CHIENLUOCUUDAI_INS TO RL_N3QLTD_LD;